"""empty message

Revision ID: 0d25c2df4a65
Revises: 5f35e9e66454
Create Date: 2020-09-15 18:05:15.257464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d25c2df4a65'
down_revision = '5f35e9e66454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('consultant', sa.String(length=100), nullable=False))
    op.drop_column('project', 'name')
    op.add_column('project', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('project', sa.Column('consultant_id', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('customer', sa.String(length=200), nullable=False))
    op.add_column('project', sa.Column('end_date', sa.String(length=10), nullable=False))
    op.add_column('project', sa.Column('manager', sa.String(length=100), nullable=False))
    op.add_column('project', sa.Column('manager_id', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('progress_percentage', sa.String(length=8), nullable=True))
    op.add_column('project', sa.Column('revised_end_date', sa.String(length=10), nullable=True))
    op.add_column('project', sa.Column('start_date', sa.String(length=10), nullable=False))
    op.add_column('project', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('project', 'team',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('project', 'project_manager')
    op.drop_column('project', 'project_consultant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_consultant', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('project_manager', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('project', 'team',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('project', 'status')
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'revised_end_date')
    op.drop_column('project', 'progress_percentage')
    op.drop_column('project', 'number')
    op.drop_column('project', 'manager_id')
    op.drop_column('project', 'manager')
    op.drop_column('project', 'end_date')
    op.drop_column('project', 'customer')
    op.drop_column('project', 'consultant_id')
    op.drop_column('project', 'consultant')
    # ### end Alembic commands ###
