"""empty message

Revision ID: 22023054c595
Revises: 68e0802aa784
Create Date: 2020-09-23 09:09:48.824473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22023054c595'
down_revision = '68e0802aa784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('time_in', sa.String(length=10), nullable=True),
    sa.Column('time_out', sa.String(length=10), nullable=True),
    sa.Column('lunch', sa.Boolean(), nullable=True),
    sa.Column('t_and_t', sa.Float(), nullable=True),
    sa.Column('personnel_id', sa.Integer(), nullable=True),
    sa.Column('personnel_name', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('target', sa.String(length=5), nullable=False),
    sa.Column('achieved', sa.String(length=5), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrolment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reassigned__task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reassigned__task')
    op.drop_table('enrolment')
    op.drop_table('task')
    op.drop_table('register')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
