"""empty message

Revision ID: 2ccfaa2cd8fb
Revises: cf8c5f2dddc5
Create Date: 2020-09-09 21:36:33.198197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccfaa2cd8fb'
down_revision = 'cf8c5f2dddc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('project', sa.Integer(), nullable=False))
    op.drop_constraint('register_project_id_fkey', 'register', type_='foreignkey')
    op.create_foreign_key(None, 'register', 'project', ['project'], ['id'])
    op.drop_column('register', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'register', type_='foreignkey')
    op.create_foreign_key('register_project_id_fkey', 'register', 'project', ['project_id'], ['id'])
    op.drop_column('register', 'project')
    # ### end Alembic commands ###
