"""empty message

Revision ID: 36fbb5b12aa3
Revises: 2ccfaa2cd8fb
Create Date: 2020-09-10 09:36:10.255882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fbb5b12aa3'
down_revision = '2ccfaa2cd8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint('register_project_fkey', 'register', type_='foreignkey')
    op.create_foreign_key(None, 'register', 'project', ['project_id'], ['id'])
    op.drop_column('register', 'project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'register', type_='foreignkey')
    op.create_foreign_key('register_project_fkey', 'register', 'project', ['project'], ['id'])
    op.drop_column('register', 'project_id')
    # ### end Alembic commands ###
