"""empty message

Revision ID: 5f35e9e66454
Revises: 70c415e9878a
Create Date: 2020-09-14 22:54:27.275282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f35e9e66454'
down_revision = '70c415e9878a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('personnel_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'personnel_name')
    # ### end Alembic commands ###
