"""empty message

Revision ID: 68e0802aa784
Revises: bc3272fc930d
Create Date: 2020-09-21 06:56:43.254827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e0802aa784'
down_revision = 'bc3272fc930d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'enrolment', 'user', ['personnel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrolment', type_='foreignkey')
    op.drop_table('user')
    # ### end Alembic commands ###
