"""empty message

Revision ID: 70c415e9878a
Revises: 9a10fed78d7e
Create Date: 2020-09-14 05:38:48.800618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c415e9878a'
down_revision = '9a10fed78d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('time_in', sa.String(length=10), nullable=True))
    op.add_column('register', sa.Column('time_out', sa.String(length=10), nullable=True))
    op.drop_column('register', 'sign_out')
    op.drop_column('register', 'sign_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('sign_in', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('register', sa.Column('sign_out', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('register', 'time_out')
    op.drop_column('register', 'time_in')
    # ### end Alembic commands ###
