"""empty message

Revision ID: 7e26971b496d
Revises: cf8c940b2bbd
Create Date: 2020-09-03 23:32:49.306156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e26971b496d'
down_revision = 'cf8c940b2bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('enrolment', sa.Column('register_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enrolment', 'register', ['register_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrolment', type_='foreignkey')
    op.drop_column('enrolment', 'register_id')
    op.drop_table('register')
    # ### end Alembic commands ###
