"""empty message

Revision ID: 91630b13df23
Revises: 22023054c595
Create Date: 2020-09-23 09:15:09.408730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91630b13df23'
down_revision = '22023054c595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task__detail',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('entry_type', sa.Integer(), nullable=False),
    sa.Column('achieved', sa.String(length=5), nullable=True),
    sa.Column('target', sa.String(length=5), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.drop_table('reassigned__task')
    op.add_column('task', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_constraint('task_project_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'date')
    op.drop_column('task', 'project_id')
    op.drop_column('task', 'comment')
    op.drop_column('task', 'target')
    op.drop_column('task', 'achieved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('achieved', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('target', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('comment', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_project_id_fkey', 'task', 'project', ['project_id'], ['id'])
    op.drop_column('task', 'date_created')
    op.create_table('reassigned__task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['task.id'], name='reassigned__task_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reassigned__task_pkey'),
    sa.UniqueConstraint('parent_id', name='reassigned__task_parent_id_key')
    )
    op.drop_table('task__detail')
    # ### end Alembic commands ###
