"""empty message

Revision ID: 9290843e677f
Revises: 36fbb5b12aa3
Create Date: 2020-09-11 08:24:11.885910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9290843e677f'
down_revision = '36fbb5b12aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('sign_in', sa.Time(), nullable=True))
    op.add_column('register', sa.Column('sign_out', sa.Time(), nullable=True))
    op.drop_column('register', 'time_in')
    op.drop_column('register', 'time_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('time_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('register', sa.Column('time_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('register', 'sign_out')
    op.drop_column('register', 'sign_in')
    # ### end Alembic commands ###
