"""empty message

Revision ID: 993b28d767fa
Revises: bf69db1bded8
Create Date: 2020-10-06 15:59:01.598228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993b28d767fa'
down_revision = 'bf69db1bded8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('creator', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'user', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'creator')
    # ### end Alembic commands ###
