"""empty message

Revision ID: 9a10fed78d7e
Revises: d801ec83615e
Create Date: 2020-09-14 05:23:13.790436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a10fed78d7e'
down_revision = 'd801ec83615e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('sign_in', sa.String(length=10), nullable=True))
    op.add_column('register', sa.Column('sign_out', sa.String(length=10), nullable=True))
    op.drop_column('register', 'time_out')
    op.drop_column('register', 'time_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('time_in', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('register', sa.Column('time_out', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('register', 'sign_out')
    op.drop_column('register', 'sign_in')
    # ### end Alembic commands ###
