"""empty message

Revision ID: bf69db1bded8
Revises: a3930a6128bb
Create Date: 2020-09-23 13:01:15.192530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf69db1bded8'
down_revision = 'a3930a6128bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task__detail', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task__detail', 'id')
    # ### end Alembic commands ###
