"""empty message

Revision ID: ce4785fd3c2a
Revises: f6d38a2b66a3
Create Date: 2020-09-18 23:27:51.795440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4785fd3c2a'
down_revision = 'f6d38a2b66a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'team')
    op.drop_column('project', 'name')
    op.drop_column('project', 'number')
    op.drop_column('project', 'status')
    op.drop_column('project', 'end_date')
    op.drop_column('project', 'actual_end_date')
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'consultant')
    op.drop_column('project', 'revised_end_date')
    op.drop_column('project', 'progress_percentage')
    op.drop_column('project', 'customer')
    op.drop_column('project', 'manager_id')
    op.drop_column('project', 'manager')
    op.drop_column('project', 'consultant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('consultant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('manager', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('customer', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('progress_percentage', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('revised_end_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('consultant', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('start_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('actual_end_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('end_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('team', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
