"""empty message

Revision ID: cf8c5f2dddc5
Revises: 64528dac70d5
Create Date: 2020-09-08 21:05:57.766203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8c5f2dddc5'
down_revision = '64528dac70d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('personnel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'personnel_id')
    # ### end Alembic commands ###
