"""empty message

Revision ID: cf8c940b2bbd
Revises: 0e8705a2bcae
Create Date: 2020-09-02 09:17:06.513137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8c940b2bbd'
down_revision = '0e8705a2bcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('comment', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'comment')
    # ### end Alembic commands ###
