"""empty message

Revision ID: d0e6fb132f5b
Revises: 993b28d767fa
Create Date: 2020-10-07 12:23:50.241223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e6fb132f5b'
down_revision = '993b28d767fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_creator_fkey', 'task', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('task_creator_fkey', 'task', 'user', ['creator'], ['id'])
    # ### end Alembic commands ###
