"""empty message

Revision ID: d801ec83615e
Revises: 7a266b7ddef9
Create Date: 2020-09-11 15:34:56.706640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd801ec83615e'
down_revision = '7a266b7ddef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('is_present', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'is_present')
    # ### end Alembic commands ###
