"""empty message

Revision ID: d8402c5b09e2
Revises: cc89bd523a2d
Create Date: 2020-10-26 09:46:05.468518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8402c5b09e2'
down_revision = 'cc89bd523a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('enrolment', sa.Column('announcement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enrolment', 'announcement', ['announcement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrolment', type_='foreignkey')
    op.drop_column('enrolment', 'announcement_id')
    op.drop_column('announcement', 'title')
    # ### end Alembic commands ###
