"""empty message

Revision ID: df6002d9db77
Revises: 7e26971b496d
Create Date: 2020-09-04 08:16:13.242910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6002d9db77'
down_revision = '7e26971b496d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'register', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'register', type_='foreignkey')
    op.drop_column('register', 'project_id')
    # ### end Alembic commands ###
