"""empty message

Revision ID: e91eb82851d4
Revises: df6002d9db77
Create Date: 2020-09-06 16:56:04.846678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91eb82851d4'
down_revision = 'df6002d9db77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('lunch', sa.Boolean(), nullable=True))
    op.add_column('register', sa.Column('time_in', sa.DateTime(), nullable=True))
    op.add_column('register', sa.Column('time_out', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'time_out')
    op.drop_column('register', 'time_in')
    op.drop_column('register', 'lunch')
    # ### end Alembic commands ###
