"""empty message

Revision ID: ed0fa9519aca
Revises: d8402c5b09e2
Create Date: 2020-10-26 10:20:43.342669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0fa9519aca'
down_revision = 'd8402c5b09e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('announcement_user_id_fkey', 'announcement', type_='foreignkey')
    op.drop_column('announcement', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('announcement_user_id_fkey', 'announcement', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
