"""empty message

Revision ID: f6d38a2b66a3
Revises: 86163593313d
Create Date: 2020-09-17 10:00:26.962296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d38a2b66a3'
down_revision = '86163593313d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('actual_end_date', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'actual_end_date')
    # ### end Alembic commands ###
